apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lzb5cezja-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lzb5cezja-java-springboot-gitops